In [12]:
import numpy as np

def get_top_10_percent_mask(matrix1, matrix2, tau=0.9):
    threshold = 1 - tau

    # Ensure the matrices have the same shape
    assert matrix1.shape == matrix2.shape, "Matrices must have the same shape"
    
    # Flatten the matrices to make the ranking easier
    flat1 = matrix1.flatten()
    flat2 = matrix2.flatten()
    
    # Get the rank indices of each element
    rank1 = np.argsort(np.argsort(-flat1))  # Ranking in descending order
    rank2 = np.argsort(np.argsort(-flat2))  # Ranking in descending order
    
    # Sum the rank indices
    sum_ranks = rank1 + rank2

    # Determine the number of top elements to select (10% of the total elements)
    num_elements = flat1.size
    top_percent_count = int(np.ceil(threshold * num_elements))
    
    # Get the indices of the top 10% elements based on the summed ranks
    top_indices = np.argsort(sum_ranks)[:top_percent_count]
    
    # Create a mask with the same shape as the original matrices
    mask = np.zeros_like(flat1, dtype=bool)
    mask[top_indices] = True
    
    # Reshape the mask to the original matrix shape
    mask = mask.reshape(matrix1.shape)
    
    return mask

# Example usage
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 9.1, 7], [6, 5, 4], [3, 2, 1]])

mask = get_top_10_percent_mask(matrix1, matrix2)
print(mask)


[8 7 6 5 4 3 2 1 0]
[1 0 2 3 4 5 6 7 8]
[9 7 8 8 8 8 8 8 8]
[[False  True False]
 [False False False]
 [False False False]]
